# To change this template, choose Tools | Templates
# and open the template in the editor.
include Containers
TERMS = Trie.new
TERMS.push("active life", "active")
TERMS.push("amusement parks", "amusementparks")
TERMS.push("aquariums", "aquariums")
TERMS.push("archery", "archery")
TERMS.push("beaches", "beaches")
TERMS.push("bike rentals", "bikerentals")
TERMS.push("boating", "boating")
TERMS.push("bowling", "bowling")
TERMS.push("climbing", "climbing")
TERMS.push("disc golf ", "discgolf")
TERMS.push("diving", "diving")
TERMS.push("free diving", "freediving")
TERMS.push("scuba diving", "scuba")
TERMS.push("fishing", "fishing")
TERMS.push("fitness & instruction", "fitness")
TERMS.push("fitness and instruction", "fitness")
TERMS.push("dance studio", "dancestudio")
TERMS.push("gyms", "gyms")
TERMS.push("martial arts", "martialarts")
TERMS.push("pilates", "pilates")
TERMS.push("swimming lessons", "swimminglessons")
TERMS.push("swimming schools", "swimminglessons")
TERMS.push("tai chi", "taichi")
TERMS.push("trainers", "healthtrainers")
TERMS.push("yoga", "yoga")
TERMS.push("go karts", "gokarts")
TERMS.push("golf", "golf")
TERMS.push("gun ranges", "gun_ranges")
TERMS.push("rifle ranges", "gun_ranges")
TERMS.push("hiking", "hiking")
TERMS.push("horse racing", "horseracing")
TERMS.push("horseback riding", "horsebackriding")
TERMS.push("Lakes", "lakes")
TERMS.push("leisure centers", "leisure_centers")
TERMS.push("mini golf", "mini_golf")
TERMS.push("mountain biking", "mountainbiking")
TERMS.push("park", "parks")
TERMS.push("dog park", "skate_parks")
TERMS.push("skate park", "golf")
TERMS.push("playground", "playgrounds")
TERMS.push("Rafting", "rafting")
TERMS.push("recreation center", "recreation")
TERMS.push("skating rink", "skatingrinks")
TERMS.push("skydiving", "skydiving")
TERMS.push("soccer", "football")
TERMS.push("sports club", "sports_clubs")
TERMS.push("summer camp", "summer_camps")
TERMS.push("swimming pool", "swimmingpools")
TERMS.push("Tennis", "tennis")
TERMS.push("zoo", "zoos")
TERMS.push("arts & entertainment", "art")
TERMS.push("arts and entertainment", "art")
TERMS.push("art & entertainment", "art")
TERMS.push("art and entertainment", "art")
TERMS.push("arts", "arts")
TERMS.push("arcade", "arcades")
TERMS.push("art galleries", "galleries")
TERMS.push("art gallery", "galleries")
TERMS.push("botanical garden", "gardens")
TERMS.push("garden", "gardens")
TERMS.push("Casino", "casinos")
TERMS.push("cinema", "movietheaters")
TERMS.push("festival", "festivals")
TERMS.push("jazz & blues", "jazzandblues")
TERMS.push("jazz and blues", "jazzandblues")
TERMS.push("museum", "museums")
TERMS.push("music venue", "musicvenues")
TERMS.push("opera & ballet", "opera")
TERMS.push("opera and ballet", "opera")
TERMS.push("performing art", "theater")
TERMS.push("theater", "theater")
TERMS.push("professional sports teams", "sportsteams")
TERMS.push("psychics & astrologers", "psychic_astrology")
TERMS.push("psychics and astrologers", "psychic_astrology")
TERMS.push("psychic & astrologers", "psychic_astrology")
TERMS.push("psychic and astrologers", "psychic_astrology")
TERMS.push("social club", "social_clubs")
TERMS.push("stadiums & arenas", "stadiumsarenas")
TERMS.push("stadiums and arenas", "stadiumsarenas")
TERMS.push("stadium", "stadiumsarenas")
TERMS.push("arena", "stadiumsarenas")
TERMS.push("wineries", "wineries")
TERMS.push("automotive", "auto")
TERMS.push("auto detailing", "auto_detailing")
TERMS.push("auto glass service", "autoglass")
TERMS.push("auto parts & supplies", "autopartssupplies")
TERMS.push("auto parts and supplies", "autopartssupplies")
TERMS.push("auto parts and supply", "autopartssupplies")
TERMS.push("auto parts & supply", "autopartssupplies")
TERMS.push("auto repair", "autorepair")
TERMS.push("body shop", "bodyshops")
TERMS.push("car dealer", "car_dealers")
TERMS.push("car stereo installation", "stereo_installation")
TERMS.push("car Wash", "carwash")
TERMS.push("gas & service station", "servicestations")
TERMS.push("gas and service station", "servicestations")
TERMS.push("motorcycle dealer", "motorcycledealers")
TERMS.push("oil change station", "oilchange")
TERMS.push("parking", "parking")
TERMS.push("smog check station", "smog_check_stations")
TERMS.push("tire", "tires")
TERMS.push("Towing", "towing")
TERMS.push("windshield installation & repair", "windshieldinstallrepair")
TERMS.push("windshield installation and repair", "windshieldinstallrepair")

puts "hello Trie"
